# -*- coding: utf-8 -*-
"""Stalyn_Gonzalez_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108eMAUmd82z1mashCFUBsWSN9OyVZ5_f

**Importación de datos**
"""

import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""**1. Análisis de facturación**"""

ingreso1 = tienda['Precio'].sum()
ingreso2 = tienda2['Precio'].sum()
ingreso3 = tienda3['Precio'].sum()
ingreso4 = tienda4['Precio'].sum()

ingresos = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Ingreso Total': [ingreso1, ingreso2, ingreso3, ingreso4]
}

ingresos_df = pd.DataFrame(ingresos)

pd.options.display.float_format = '{:,.2f}'.format

print(ingresos_df)

ingresos = [
    tienda['Precio'].sum(),
    tienda2['Precio'].sum(),
    tienda3['Precio'].sum(),
    tienda4['Precio'].sum()
]

nombres_tiendas = ['Store 1', 'Store 2', 'Store 3', 'Store 4']

plt.figure(figsize=(8,5))
bars = plt.barh(nombres_tiendas, ingresos, color='mediumseagreen')
plt.title('Total Revenue per Store')
plt.xlabel('Income (in monetary units)')
plt.ylabel('Store')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.gca().invert_yaxis()

for bar in bars:
    width = bar.get_width()
    plt.text(width + width * 0.01, bar.get_y() + bar.get_height() / 2,
             f'{width:,.0f}', va='center')

plt.savefig('Ingresos_totales_por_tienda.png')
plt.show()
plt.close()

"""**2. Ventas por categoría**"""

def contar_productos_por_categoria(df, nombre_tienda):
    conteo = df['Categoría del Producto'].value_counts().reset_index()
    conteo.columns = ['Categoría', 'Cantidad Vendida']
    conteo['Tienda'] = nombre_tienda
    return conteo

categorias_tienda = contar_productos_por_categoria(tienda, 'Tienda 1')
categorias_tienda2 = contar_productos_por_categoria(tienda2, 'Tienda 2')
categorias_tienda3 = contar_productos_por_categoria(tienda3, 'Tienda 3')
categorias_tienda4 = contar_productos_por_categoria(tienda4, 'Tienda 4')

categorias_totales = pd.concat([categorias_tienda, categorias_tienda2, categorias_tienda3, categorias_tienda4])

print(categorias_totales)

import matplotlib.pyplot as plt

tiendas = [tienda, tienda2, tienda3, tienda4]
nombres_tiendas = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

for i, (df, nombre) in enumerate(zip(tiendas, nombres_tiendas), start=1):
    categorias = df['Categoría del Producto'].value_counts()

    plt.figure(figsize=(6, 6))
    plt.pie(categorias, labels=categorias.index, autopct='%1.1f%%',
            startangle=140, colors=plt.cm.Set3.colors)

    plt.title(f'Distribución de Categorías - {nombre}')

    archivo_individual = f'distribucion_categorias_{nombre.lower().replace(" ", "_")}.png'
    plt.savefig(archivo_individual, bbox_inches='tight')


    plt.show()
    plt.close()
    print("\n" + "-"*80 + "\n")

"""**3. Calificación promedio de la tienda**"""

def promedio_calificacion(df):
    return df['Calificación'].mean()

promedio1 = promedio_calificacion(tienda)
promedio2 = promedio_calificacion(tienda2)
promedio3 = promedio_calificacion(tienda3)
promedio4 = promedio_calificacion(tienda4)

promedios = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Promedio de Calificación': [promedio1, promedio2, promedio3, promedio4]
}

promedios_df = pd.DataFrame(promedios)

print(promedios_df)

import seaborn as sns
import matplotlib.pyplot as plt

promedios_calificacion = [
    tienda['Calificación'].mean(),
    tienda2['Calificación'].mean(),
    tienda3['Calificación'].mean(),
    tienda4['Calificación'].mean()
]

nombres_tiendas = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

import pandas as pd
calificaciones_df = pd.DataFrame({
    'Tienda': nombres_tiendas,
    'Promedio de Calificación': promedios_calificacion
})

calificaciones_df = calificaciones_df.sort_values('Promedio de Calificación', ascending=False)

plt.figure(figsize=(8,5))
ax = sns.barplot(
    data=calificaciones_df,
    y='Tienda',
    x='Promedio de Calificación',
    palette='crest'
)

for i in ax.containers:
    ax.bar_label(i, fmt='%.4f', label_type='edge', padding=3)

plt.title('Promedio de Calificaciones por Tienda', fontsize=14)
plt.xlim(0, 5)
plt.xlabel('Promedio de Calificación')
plt.ylabel('Tienda')
plt.grid(axis='x', linestyle='--', alpha=0.7)

plt.savefig('Promedio_de_Calificaciones_por_Tienda.png')
plt.show()
plt.close()

"""**4. Productos más y menos vendidos**"""

def productos_extremos(df, nombre_tienda):
    conteo = df['Producto'].value_counts()

    mas_vendido = conteo.idxmax()
    ventas_mas_vendido = conteo.max()

    menos_vendido = conteo.idxmin()
    ventas_menos_vendido = conteo.min()

    print(f"\n{nombre_tienda}")
    print(f"Producto más vendido: {mas_vendido} ({ventas_mas_vendido} ventas)")
    print(f"Producto menos vendido: {menos_vendido} ({ventas_menos_vendido} ventas)")


productos_extremos(tienda, 'Tienda 1')
productos_extremos(tienda2, 'Tienda 2')
productos_extremos(tienda3, 'Tienda 3')
productos_extremos(tienda4, 'Tienda 4')

"""**5. Envío promedio por tienda**"""

def promedio_costo_envio(df):
    return df['Costo de envío'].mean()

promedio_envio1 = promedio_costo_envio(tienda)
promedio_envio2 = promedio_costo_envio(tienda2)
promedio_envio3 = promedio_costo_envio(tienda3)
promedio_envio4 = promedio_costo_envio(tienda4)

costos_envio = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Costo de Envío Promedio': [promedio_envio1, promedio_envio2, promedio_envio3, promedio_envio4]
}

costos_envio_df = pd.DataFrame(costos_envio)

print(costos_envio_df)

"""# **Ganancia**

Si asumimos que la única inversión/costo es el envío, puedo calcular como Ganancia:

Ganancia = Precio - Costo de envío

    Tienda 1: $1,089,502,500.00 unidades monetarias

    Tienda 2: $1,056,858,400.00 unidades monetarias

    Tienda 3: $1,039,503,000.00 unidades monetarias

    Tienda 4: $983,058,300.00 unidades monetarias

Siendo la Tienda 1 la que mas Ganancia daría al Sr Juan.
"""

ganancia1 = (tienda['Precio'] - tienda['Costo de envío']).sum()
ganancia2 = (tienda2['Precio'] - tienda2['Costo de envío']).sum()
ganancia3 = (tienda3['Precio'] - tienda3['Costo de envío']).sum()
ganancia4 = (tienda4['Precio'] - tienda4['Costo de envío']).sum()

ganancias = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Ganancia Total': [ganancia1, ganancia2, ganancia3, ganancia4]
}

ganancias_df = pd.DataFrame(ganancias)
print(ganancias_df)

"""# **Ganancia**

Si asumimos que la única inversión/costo es el envío, puedo calcular como Ganancia:

Ganancia = Precio - Costo de envío

    Tienda 1: $1,089,502,500.00 unidades monetarias

    Tienda 2: $1,056,858,400.00 unidades monetarias

    Tienda 3: $1,039,503,000.00 unidades monetarias

    Tienda 4: $983,058,300.00 unidades monetarias

Siendo la Tienda 1 la que mas Ganancia daría al Sr Juan.
"""

import matplotlib.pyplot as plt

ganancia1 = (tienda['Precio'] - tienda['Costo de envío']).sum()
ganancia2 = (tienda2['Precio'] - tienda2['Costo de envío']).sum()
ganancia3 = (tienda3['Precio'] - tienda3['Costo de envío']).sum()
ganancia4 = (tienda4['Precio'] - tienda4['Costo de envío']).sum()

ganancias = [ganancia1, ganancia2, ganancia3, ganancia4]
nombres_tiendas = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

plt.figure(figsize=(8,5))
bars = plt.barh(nombres_tiendas, ganancias, color='mediumorchid')
plt.title('Ganancia Total por Tienda')
plt.xlabel('Ganancia (en unidades monetarias)')
plt.grid(axis='x', linestyle='--', alpha=0.7)

for bar in bars:
    width = bar.get_width()
    plt.text(width + 10000, bar.get_y() + bar.get_height()/2,
             f'{int(width):,}', va='center')

plt.tight_layout()
plt.show()

"""
# Informe Final de Análisis de Tiendas
**Introducción**

El objetivo de este análisis fue determinar en qué tienda debería vender sus productos el Sr. Juan. Para ello, analizamos los ingresos totales de cada tienda, las categorías de productos más y menos vendidas, las calificaciones promedio de los clientes, los productos destacados en ventas y el costo promedio de envío. Estos factores son claves para entender cuál tienda ofrece mayores oportunidades de éxito comercial.
# Ingresos Totales

Se calcularon los ingresos sumando los precios de venta de todos los productos en cada tienda. El análisis mostró que:

Tienda 1 tuvo ingresos de 1,150,880,400.00 unidades monetarias.

Tienda 2 tuvo ingresos de 1,116,343,500.00 unidades monetarias.

Tienda 3 tuvo ingresos de 1,098,019,600.00 unidades monetarias.

Tienda 4 tuvo ingresos de 1,038,375,700.00 unidades monetarias.

La Tienda 1 generó los mayores ingresos, indicando un volumen de ventas más fuerte.

Gráfico de barras mostrado: Ingresos Totales por Tienda, a continuación:
"""

from IPython.display import Image, display

display(Image('Ingresos_totales_por_tienda.png'))

"""# Distribución de Categorías

Se analizó la distribución de ventas por categorías de productos en todas las Tiendas.

**El gráfico de pastel mostró que las categorías "Muebles","Electrónicos", "Juguetes","Electrodomésticos" y "Deportes y diversión" fueron las más populares en las Tiendas 1,2 y 3, mientras que la Tienda 4 no coincide con esas categorias como las más populares.**

**La categorías "Artículos para el hogar"tuvo menor participación en las Tiendas 1,2 y 3, pero no en la Tienda 4. **

Esto es relevante para alinear el tipo de producto que el Sr. Juan podría vender.

A continuación se puede ver los gráficos de Distribución de Categorías por Tienda, su método de pago y categoría vs precio:
"""

display(Image('distribucion_categorias_tienda_1.png'))
print("\n" + "-"*80 + "\n")
display(Image('distribucion_categorias_tienda_2.png'))
print("\n" + "-"*80 + "\n")
display(Image('distribucion_categorias_tienda_3.png'))
print("\n" + "-"*80 + "\n")
display(Image('distribucion_categorias_tienda_4.png'))

# @title Categoría del Producto vs Método de pago

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Método de pago'].value_counts()
    for x_label, grp in tienda.groupby('Categoría del Producto')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Categoría del Producto')
_ = plt.ylabel('Método de pago')

# @title Categoría del Producto vs Precio

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(tienda['Categoría del Producto'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(tienda, x='Precio', y='Categoría del Producto', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

"""# Calificaciones Promedio

Analizando la satisfacción del cliente:

Tienda 1: promedio de 3,9767 estrellas.

Tienda 2: promedio de 4,0373 estrellas.

Tienda 3: promedio de 4,0483 estrellas.

Tienda 4: promedio de 3,9958 estrellas.

**La tienda con la mejor satisfacción fue Tienda 3, lo cual sugiere clientes más contentos y posiblemente mayor fidelidad.**

Gráfico de barras mostrado: Promedio de Calificaciones por Tienda, a continuación:
"""

from IPython.display import Image, display

display(Image('Promedio_de_Calificaciones_por_Tienda.png'))

"""# Productos más y menos vendidos

Se identificaron los productos más populares en cada tienda.

Tienda 1 Producto más vendido: Microondas (60 ventas) Producto menos vendido: Auriculares con micrófono (33 ventas)

Tienda 2 Producto más vendido: Iniciando en programación (65 ventas) Producto menos vendido: Juego de mesa (32 ventas)

Tienda 3 Producto más vendido: Kit de bancas (57 ventas) Producto menos vendido: Bloques de construcción (35 ventas)

Tienda 4 Producto más vendido: Cama box (62 ventas) Producto menos vendido: Guitarra eléctrica (33 ventas)

Esto permite entender qué productos tienen más demanda y ajustar la oferta si es necesario.
"""

import matplotlib.pyplot as plt

colores_tienda = {
    'Tienda 1': 'mediumseagreen',
    'Tienda 2': 'steelblue',
    'Tienda 3': 'darkorange',
    'Tienda 4': 'orchid'
}

def productos_extremos(df, nombre_tienda):
    conteo = df['Producto'].value_counts()

    mas_vendido = conteo.idxmax()
    ventas_mas_vendido = conteo.max()

    menos_vendido = conteo.idxmin()
    ventas_menos_vendido = conteo.min()

    print(f"\n{nombre_tienda}")
    print(f"Producto más vendido: {mas_vendido} ({ventas_mas_vendido} ventas)")
    print(f"Producto menos vendido: {menos_vendido} ({ventas_menos_vendido} ventas)")

    top5 = conteo.head(5)

    plt.figure(figsize=(8,5))
    top5.plot(kind='bar', color=colores_tienda[nombre_tienda])
    plt.title(f'Top 5 Productos Más Vendidos - {nombre_tienda}')
    plt.ylabel('Cantidad Vendida')
    plt.xticks(rotation=45)
    plt.grid(axis='y', linestyle='--', alpha=0.6)
    plt.tight_layout()

    nombre_archivo = f'top5_productos_{nombre_tienda.lower().replace(" ", "_")}.png'
    plt.savefig(nombre_archivo, dpi=300)
    plt.show()

productos_extremos(tienda, 'Tienda 1')
productos_extremos(tienda2, 'Tienda 2')
productos_extremos(tienda3, 'Tienda 3')
productos_extremos(tienda4, 'Tienda 4')

"""# Costos de Envío Promedio

El costo de envío promedio en cada tienda fue:

    **Tienda 1: $26019 unidades monetarias**

    **Tienda 2: $25216 unidades monetarias**

    **Tienda 3: $24806 unidades monetarias**

    **Tienda 4: $23459 unidades monetarias**

Tiendas con costos de envío más bajos pueden representar una ventaja competitiva para los clientes.
"""

import seaborn as sns
import matplotlib.pyplot as plt

costos_envio = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Costo de Envío Promedio': [promedio_envio1, promedio_envio2, promedio_envio3, promedio_envio4]
}
costos_envio_df = pd.DataFrame(costos_envio)

plt.figure(figsize=(8, 5))
ax = sns.barplot(
    data=costos_envio_df,
    y='Tienda',
    x='Costo de Envío Promedio',
    palette='YlGnBu'
)

for container in ax.containers:
    ax.bar_label(container, fmt='%.0f', label_type='edge', padding=5)

plt.title('Costo de Envío Promedio por Tienda')
plt.xlabel('Costo Promedio de Envío')
plt.ylabel('Tienda')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()

plt.savefig('costo_envio_promedio_por_tienda.png')
plt.show()

"""# Análisis del desempeño geográfico

El primer gráfico usa:

    

1.   lon y lat como ubicación.
2.   El tamaño de los puntos para representar el precio del producto.
3. El color para reflejar la calificación del cliente.



"""

import seaborn as sns
import matplotlib.pyplot as plt

tiendas = [tienda, tienda2, tienda3, tienda4]
nombres_tiendas = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

for df, nombre in zip(tiendas, nombres_tiendas):
    plt.figure(figsize=(8,6))
    sns.scatterplot(x='lon', y='lat', size='Precio', hue='Calificación', data=df, palette='viridis', sizes=(20, 200), alpha=0.6)
    plt.title(f'Distribución Geográfica de Ventas - {nombre}')
    plt.xlabel('Longitud')
    plt.ylabel('Latitud')
    plt.legend(title='Calificación')
    plt.grid(True)
    print("\n" + "-"*80 + "\n")
    plt.show()

"""# HeatMap de Ventas

Este mapa muestra todas las ventas de las 4 tiendas, calcula el centro del mapa basado en el promedio de latitudes y longitudes, y através del HeatMap representa visualmente las zonas con más puntos de venta.Los puntos más “calientes” (más ventas) se verán con más intensidad.
"""

import folium
from folium.plugins import HeatMap
import pandas as pd

df_total = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

mapa_calor = folium.Map(location=[df_total['lat'].mean(), df_total['lon'].mean()], zoom_start=4)

heat_data = df_total[['lat', 'lon']].values.tolist()
HeatMap(heat_data, radius=12).add_to(mapa_calor)

mapa_calor

"""# Conclusión

Basándonos en el análisis realizado, se recomienda que el Sr. Juan venda en la Tienda 4. La tienda 4:


1.   Tiene el menor ingreso total, siendo la Tienda 1 la que indica el mayor ingreso total y tener un mercado más activo.
2.   No presenta altas calificaciones de satisfacción por parte de los clientes, es la anteúltima en la lista, siendo la Tienda 3 la que tiene altas calificaciones de satisfacción por parte de los clientes.
3. No cuenta con categorías de productos más vendidas alineadas al perfil de productos que el Sr. Juan puede ofrecer, donde las Tiendas 1,2 y 3 tienen las primeras categorias mas vendidas.
4. Tiene los costos de envío mas bajos, pero su ganancia es la menor. A diferencia de la Tienda 1 que mejora la competitividad con una mejor relacion Costos de envío/ingresos totales.
5. El mapa muestra visualmente donde se encuentran las mayores ventas según la Tienda y su latitud y longitud, predominando la Tienda 1 por tener mejor relacion costo de envío/Ventas.

**Por lo tanto, la Tienda 4 representa la peor oportunidad para maximizar las ventas y la satisfacción del cliente, no garantiza un negocio rentable y sostenible.Y por ende Sr. Juan debería vender la Tienda 4.**
"""